title: Azure Developer College
patterns: ['**/*.md', '!**/node_modules', '!templates/**']
base: /
themeConfig:
  repo: 'razumovskii/trainingdays'
  editLinks: true
  sidebar:
    [
      ['./', 'Home'],
      './day1/',
      './day2/',
      './day3/',
      './day4/',
      './day5/',
      './day6/',
      './day7/',
    ]
plugins: [['vuepress-plugin-code-copy', true]]
