name: pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - run: npm init -y
        
      - run: npm install vuepress vuepress-plugin-code-copy
        
      - run: node_modules/.bin/vuepress build
        
      - name: Upload result of vuepress build
        uses: actions/upload-artifact@v4
        with:
          name: static-website
          path: .vuepress/dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build of static website
        uses: actions/download-artifact@v4
        with:
          name: static-website
          path: .vuepress/dist
          
      - name: Clone repository and copy files
        run: |
          git clone https://$TOKEN@github.com/razumovskii/razumovskii.github.io ~/razumovskii/razumovskii.github.io
          rm -r ~/razumovskii/razumovskii.github.io/*
          cp -R ~/.vuepress/dist/* ~/razumovskii/razumovskii.github.io
        env:
          TOKEN: ${{ secrets.DEPLOY_TOKEN }}

      - name: Commit changes if any
        run: |
          cd ~/razumovskii/razumovskii.github.io
          git config --global user.name "$USERNAME"
          git config --global user.email "$EMAIL"
          git status
          git add .
          git commit -m "$MESSAGE"
          git push
        env:
          USERNAME: "razumovskii"
          EMAIL: "rzaumovskey@gmail.com"
          MESSAGE: "CICD deploy to git pages"